### ISSUE TITLE
no supported sources

### ISSUE THREAD

**Issue by beiyanpiki** [LarchLiu/playcore-hls#1]
I use vue3-ts. And everything is ok in Vue3 Video Player, but I got something error after import ``playcore-hls`` plugin.

VideoPlayer.vue
```vue
<template>
    <vue3-video-player
        @play="videoProps.playFunc"
        :core="core"
        :src="videoProps.source"
        :title="videoProps.title"
        :view-core="videoProps.viewCore"
        :cover="videoProps.cover"
        :key="videoProps.id"
    />
</template>

<script lang="ts">
import { computed, defineComponent } from "vue";
import core from '@cloudgeek/playcore-hls';


export default defineComponent({
    name: "HomePage",
    setup() {
        const videoProps = {
               // some video props here...
        }
       
        return { videoProps , core }
    }
})
</script>
```

And I got 
```
hls.js@latest:1 Uncaught TypeError: e.trim is not a function
    at Object.buildAbsoluteURL (hls.js@latest:1)
    at t.l.loadSource (hls.js@latest:1)
    at src_HLSCore.initHLSCore (index.js:31)
    at index.js:19
    at index.js:75
    at HTMLScriptElement.script.onload (index.js:49)

vue3-video-player.common.js:23503 Uncaught (in promise) DOMException: The element has no supported sources.
```
![image](https://user-images.githubusercontent.com/36980069/118008915-26054f00-b380-11eb-8d21-1393385dff0e.png)

**Comment by beiyanpiki** [comment]
Well, it's not ts issue. I found if I use constant src is ok.
```vue
    <vue3-video-player
        src="http://video.path/test.mp4"
        @play="videoProps.playFunc"
        :title="videoProps.title"
        :cover="videoProps.cover"
        :key="videoProps.id"
         :core="core"
    ></vue3-video-player>
```

but when I use v-bind:src got error
```vue
    <vue3-video-player
        src="videoProps.source"
        @play="videoProps.playFunc"
        :title="videoProps.title"
        :cover="videoProps.cover"
        :key="videoProps.id"
        :core="core"
    ></vue3-video-player>
```

if I delete ``:core="core"`` everything is ok

**Comment by LarchLiu** [comment]
change src to http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8 and test.
this plugin is used in m3u8 format.

**Comment by beiyanpiki** [comment]
The code below didn't get the expectation
```vue
 <vue3-video-player
        :src="videoProps.source"
        :title="videoProps.title"
        :cover="videoProps.cover"
        :key="videoProps.id"
        :core="HLSCore"
    ></vue3-video-player>
   <pre>{{videoProps}} </pre>
```
```vue
const videoProp = ref({
            "id": "609ba205e5f541a6dd6e3d19",
            "source": [
                {
                    "src": "https://tx1.yunchuanglive.com/live/SSAC-112680-EBFFB.m3u8",
                    "resolution": "raw"
                }
            ],
            "title": "123",
            "cover": "/ybvideo/resource/12333.jpg"
        })
```
![image](https://user-images.githubusercontent.com/36980069/118029615-e9911d80-b396-11eb-8d2e-bd27e2edbab4.png)
But this code it's ok 
```vue
    <vue3-video-player
        src="https://tx1.yunchuanglive.com/live/SSAC-112680-EBFFB.m3u8"
        :title="videoProp.title"
        :cover="videoProp.cover"
        :core="HLSCore"
    ></vue3-video-player>
    <pre>{{videoProps}} </pre>
```
![image](https://user-images.githubusercontent.com/36980069/118029800-17766200-b397-11eb-8a50-623232eea4d7.png)

**Comment by LarchLiu** [comment]
videoProp should like below, and use v-bind as    :src='videoProp.source'
```
const videoProp = ref({
            "id": "609ba205e5f541a6dd6e3d19",
            "source":  "https://tx1.yunchuanglive.com/live/SSAC-112680-EBFFB.m3u8",
            "title": "123",
            "cover": "/ybvideo/resource/12333.jpg"
        })
```

**Comment by LarchLiu** [comment]
if don't change videoProp just set :src='videoProp.source[0].src'

**Comment by LarchLiu** [comment]
I'll change to check src by hlscore to make it consistent with basecore.

**Comment by LarchLiu** [comment]
🎉  new version release: 

plugin v0.1.2 and vue3-video-player v0.3.2

🤘 enjoy & feedback

**Comment by beiyanpiki** [comment]
Wow, thanks a lot.

**Comment by beiyanpiki** [comment]
Em, I think there is a new trouble. I update package to new version, but got something error from vite. 

```
3:41:51 PM [vite] Internal server error: Failed to resolve entry for package "@cloudgeek/vue3-video-player". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /home/beiyanpiki/Project/yiban-video/web/src/main.ts
      at resolvePackageEntry (/home/beiyanpiki/Project/yiban-video/web/node_modules/vite/dist/node/chunks/dep-efbff8d5.js:32450:15)
      at tryNodeResolve (/home/beiyanpiki/Project/yiban-video/web/node_modules/vite/dist/node/chunks/dep-efbff8d5.js:32269:11)
      at Context.resolveId (/home/beiyanpiki/Project/yiban-video/web/node_modules/vite/dist/node/chunks/dep-efbff8d5.js:32152:28)
      at Object.resolveId (/home/beiyanpiki/Project/yiban-video/web/node_modules/vite/dist/node/chunks/dep-efbff8d5.js:44098:55)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at async TransformContext.resolve (/home/beiyanpiki/Project/yiban-video/web/node_modules/vite/dist/node/chunks/dep-efbff8d5.js:43903:23)
      at async normalizeUrl (/home/beiyanpiki/Project/yiban-video/web/node_modules/vite/dist/node/chunks/dep-efbff8d5.js:68831:34)
      at async TransformContext.transform (/home/beiyanpiki/Project/yiban-video/web/node_modules/vite/dist/node/chunks/dep-efbff8d5.js:68961:57)
      at async Object.transform (/home/beiyanpiki/Project/yiban-video/web/node_modules/vite/dist/node/chunks/dep-efbff8d5.js:44155:30)
      at async transformRequest (/home/beiyanpiki/Project/yiban-video/web/node_modules/vite/dist/node/chunks/dep-efbff8d5.js:58421:29)
```

And same error by using vue-babel.

**Comment by LarchLiu** [comment]
How ablout v0.3.1? 
Pls check vue3-video-player v0.3.1 + hlsplugin v0.1.2 
If v0.3.1 is ok , i will rebuild a new version for vue3-video-player.

**Comment by LarchLiu** [comment]
And pls check vue3-video-player v0.3.3 + hlsplugin v0.1.2
Looking forward to your feedback.

**Comment by beiyanpiki** [comment]
It works! Thank you for your patience! 👍 👍 👍
